### ISSUE TITLE
Docker on x86

### ISSUE THREAD

**Issue by oscarthorn** [NVIDIA-AI-IOT/ros2_trt_pose#6]
Hi!

Can the docker container for this repo be built on a x86 machine? I have qemu added, cuda cross compile libraries and nvidia-docker but I get the error

`Cloning into 'torch2trt'...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    import torch
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 188, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 141, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory
`

**Comment by ak-nv** [comment]
The base image we provided for the docker is built on L4T ie specific to NVIDIA Jetson. Thus will not work for x86.
You can probably use Docker File [here](https://github.com/NVIDIA-AI-IOT/ros2_jetson/tree/main/docker) and change base image. 

Closing this as it is not Jetson related, please reopen if more questions.
